project:
  type: website
  output-dir: docs

website:
  title: "Diário de Ecologia de Paisagens - Bruna Batista"
  navbar:
    background: "#2f4f4f"
    type: dark
    right:
      - href: index.qmd
        text: Início
      - text: "Relatórios"
        menu:
         - href: relatorio_aula1.qmd
           text: "Relatório — Aula 1"
         - href: relatorio_aula2.qmd
           text: "Relatório — Aula 2"
         - href: relatorio_aula3.qmd
           text: "Relatório — Aula 3"
      - text: "Exercícios"
        menu:
         - href: ex1.qmd
           text: "EX1"
         - href: ex2.qmd
           text: "EX2"
         - href: ex3.qmd
           text: "EX3"
         - href: ex4.qmd
           text: "EX4"
         - href: ex5.qmd
           text: "EX5"
      - text: "Avaliação final"
      
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true        # Adiciona a caixinha de "clicar para ver"
    code-summary: "Mostrar código"