project:
  type: website
  output-dir: docs

website:
  title: "Diário de Ecologia de Paisagens - Bruna Batista"
  navbar:
    left:
      - href: index.qmd
        text: Início
      - href: relatorio_aula1.qmd
        text: "Relatório — Aula 1"
      - href: relatorio_aula2.qmd
        text: "Relatório — Aula 2"
      - href: relatorio_aula3.qmd
        text: "Relatório — Aula 3"
      - href: ex1.qmd
        text: "EX1"
      - href: ex2.qmd
        text: "EX2"
      - href: ex3.qmd
        text: "EX3"
      - href: ex4.qmd
        text: "EX4"
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true

editor: visual
